version: "3"
services:
  typescript-local:
    container_name: typescript-local
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5000"
    volumes:
      - ./src:/usr/app/src